### ISSUE TITLE
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'max_pooling2d_2/MaxPool'

### ISSUE THREAD

**Issue by simon-gunacker** [iamaaditya/VQA_Demo#12]
Hey, 

I am getting the error mentioned above when trying to run this code:

`from keras.utils.vis_utils import plot_model
model_vgg = get_image_model(CNN_weights_file_name)
model_vgg.add(MaxPooling2D(pool_size=(2, 2), dim_ordering="th"))
plot_model(model_vgg, to_file='model_vgg.png')`

Any ideas how to fix this?

thanks, simon

**Comment by iamaaditya** [comment]
@simon-gunacker  What version of Keras and Tensorflow are you using?

**Comment by michael20at** [comment]
Hi, I've got the same problem, long error list on 

model_vgg = get_image_model(CNN_weights_file_name)

which derives from: image_model = VGG_16(CNN_weights_file_name)

I have TF 1.2 and Keras 2.05, downloaded VGG16 Weights, as mentioned in the readme. Any idea? 

Thank you, Mike

**Comment by michael20at** [comment]
Hi, 

solved it myself already, for anyone interested, it's a problem with keras implementation of VGG16 weights.

Just add 

`from keras import backend as K

K.set_image_dim_ordering('th')`

at the top!

Greetings, Mike

**Comment by Kishwar** [comment]
@michael20at Thanks - Working now.
