### ISSUE TITLE
ValueError: Error when checking : expected lstm_4_input to have shape (None, 30, 300)

### ISSUE THREAD

**Issue by michael20at** [iamaaditya/VQA_Demo#14]
Hi,

i get 

ValueError: Error when checking : expected lstm_4_input to have shape (None, 30, 300) but got array with shape (1, 7, 300)

on y_output = model_vqa.predict([question_features, image_features])

Any idea why?

Thanks for your help! 

fG Mike

Update: I found out that the problem is "len(tokens)"! The question was seven tokens long.

If I change "len(tokens" to "30" it works, but don't think that should be right?

**Comment by michael20at** [comment]
It works when i use demo.py after some corrections, error remains only in the notebook.

I think the problem is that I use Python 3 and you used 2, because I had to change some things in demo.py to get it to run (range instead of xrange, no unicode, str parentheses, etc.), after that demo.py worked!

**Comment by iamaaditya** [comment]
Yes, I have not updated the Notebook in a while. If you have a working
version of the notebook I would be willing to accept a pull request.

Thanks and Regards
Adi
