### ISSUE TITLE
Value Error: Unknown Layer: Merge

### ISSUE THREAD

**Issue by Archan2607** [iamaaditya/VQA_Demo#22]
![image](https://user-images.githubusercontent.com/35597922/46432470-f9bad800-c76b-11e8-80fd-9f77ecdc873a.png)

Hi,

I am working on the code given in ipython notebook and tried to solve every possible thing to solve the issue but it is not happening

I have also uploaded the image

I am very interested in the work done by you, please help me out.

Thank You

**Comment by iamaaditya** [comment]
The notebook has not been updated with changes in Keras. Use the python file (demo.py) to run the code. If you want to use Notebook, copy and paste the relevant functions from the python file.

**Comment by WrathofBhuvan11** [comment]
> The notebook has not been updated with changes in Keras. Use the python file (demo.py) to run the code. If you want to use Notebook, copy and paste the relevant functions from the python file.

Can you provide us the new weight file for Keras 2.0+ version..?

**Comment by AmrataRamchandani** [comment]
@iamaaditya  Even the demo.py file has that error

Can you please update your code as well as weight file for latest version of keras ?

**Comment by Utsavjain4561** [comment]
@iamaaditya  can you please provide new weight file for keras 2.0+ version 
i am getting 'you are trying to load a weight file containing 7 layers into a model with 0 layers when using Reshape'
I am really interested in your work !!
