### ISSUE TITLE
Error predicting 

### ISSUE THREAD

**Issue by prem1215** [iamaaditya/VQA_Demo#26]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-66-dd3bee432810> in <module>
      8 labelencoder = joblib.load(label_encoder_file_name)
      9 for label in reversed(np.argsort(y_output)[0,-5:]):
---> 10     print(str(round(y_output[0,label]*100,2)).zfill(5), "% ",labelencoder.inverse_transform(label))

~\Anaconda3\envs\VQA1\lib\site-packages\sklearn\preprocessing\label.py in inverse_transform(self, y)
    271         """
    272         check_is_fitted(self, 'classes_')
--> 273         y = column_or_1d(y, warn=True)
    274         # inverse transform of empty array is empty array
    275         if _num_samples(y) == 0:

~\Anaconda3\envs\VQA1\lib\site-packages\sklearn\utils\validation.py in column_or_1d(y, warn)
    795         return np.ravel(y)
    796 
--> 797     raise ValueError("bad input shape {0}".format(shape))
    798 
    799 

ValueError: bad input shape ()

**Comment by WeiYangBin** [comment]
Hello, I also encountered this problem. Have you solved it

**Comment by WeiYangBin** [comment]
I have solved the problem, we only need:
```
print("{} % {}!".format(round(y_output[0,label]*100,2), labelencoder.inverse_transform([label])[0]))
```
Because the inverse transform requires that we pass in an array

**Comment by jiteshm17** [comment]
@WeiYangBin thank you so much for this. However, one thing to note is that this only works if the `scikit-learn` version is `0.21.1`
