### ISSUE TITLE
Can't access the download link of the drive for vgg16_weights.h5

### ISSUE THREAD

**Issue by hirafs** [iamaaditya/VQA_Demo#38]
Kindly place the h5 model on the drive link for **vgg16_weights.h5**
![image](https://user-images.githubusercontent.com/68616232/109345378-db505c80-7891-11eb-84b3-b198e0ab948f.png)

**Comment by iamaaditya** [comment]
Try this: 
https://drive.google.com/file/d/1xJbtMZzKv62PaohN1fRySZR6l9gHTz6Z/view?usp=sharing

**Comment by hirafs** [comment]
Thank you, the issue is resolved

**Comment by TheKOG** [comment]
> Try this: https://drive.google.com/file/d/1xJbtMZzKv62PaohN1fRySZR6l9gHTz6Z/view?usp=sharing

It's also broken
