### ISSUE TITLE
I am having this issue in the last step, 'NoneType' object has no attribute 'zfill'

### ISSUE THREAD

**Issue by hirafs** [iamaaditya/VQA_Demo#39]
![image](https://user-images.githubusercontent.com/68616232/109493693-aff68900-7aae-11eb-967d-2418ff5ddd08.png)

**Comment by Myomyoo** [comment]
hello there, I have the same problem. Did you solved it by changing the sklearn version? And which version, plz.

**Comment by hirafs** [comment]
This solved my problem. I loaded the npy file directly 

warnings.filterwarnings("ignore", category=DeprecationWarning)
m = np.load(label_encoder_file_name)
labels_list=[]
for label in reversed(np.argsort(y_output)[0,-5:]):
    print ((str(round(y_output[0,label]*100,2))).zfill(5), "% ", m[label])
