### ISSUE TITLE
Inconsistent dimensions in VQA json model

### ISSUE THREAD

**Issue by anujkhare** [iamaaditya/VQA_Demo#8]
Hi, thanks for the repo!

In the function `get_question_features`:
Ipython notebook uses np array of size `(1, len(tokens), 300` for the `question_tensor`, while `demo.py` uses `(1, 30, 300)`. The json model also uses the latter.

Ipython notebook produces an error at this function.

**Comment by iamaaditya** [comment]
When Keras updated from 0.3 to 1.0, it changed quite a few things, and thus I had to change the code. I only changed `demo.py`. So use only that. If you look closely the IPython Notebook is just the same functions but with more interactive examples. You can literally copy paste demo.py to notebook file and break the functions and execute the code.

**Comment by anujkhare** [comment]
Thanks, I got it to work. Maybe add a small note in readme?

**Comment by iamaaditya** [comment]
Sure. Will do, thanks.
Close #8
